language: node_js
node_js:
  - 10
cache:
  yarn: true
script:
  - yarn run build-prod && mv ./build/index.html ./build/200.html
deploy:
  provider: surge
  project: ./build/
  domain: fresh-mint.j4id.com
  skip_cleanup: true
