language: node_js
node_js:
  - 10
cache:
  yarn: true
script:
  - yarn run build-prod && cp ./build/index.html ./build/404.html
deploy:
  provider: pages
  local-dir: ./build/
  fqdn: j4id.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
