language: node_js
node_js:
  - 10
cache:
  yarn: true
script:
  - yarn run build-prod && mv ./build/index.html ./build/200.html
deploy:
  provider: pages
  local-dir: ./build/
  fqdn: fresh-mint.j4id.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
